# Generated by Django 4.1.5 on 2023-03-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k12Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldetail',
            name='grades',
        ),
    ]
