# Generated by Django 4.1.5 on 2023-02-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
