# Generated by Django 4.1.5 on 2023-03-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12Api', '0002_remove_schooldetail_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
