# Generated by Django 4.1.5 on 2023-03-21 03:11

from django.db import migrations, models
import k12Api.models


class Migration(migrations.Migration):

    dependencies = [
        ('k12Api', '0004_alter_users_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=k12Api.models.picturePath),
        ),
    ]
