# Generated by Django 4.1.5 on 2023-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12Api', '0005_schooldetail_state_alter_users_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
