# Generated by Django 4.1.5 on 2023-03-22 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12Api', '0006_schooldetail_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='grades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512), blank=True, null=True, size=None),
        ),
    ]
