# Generated by Django 4.1.5 on 2023-03-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12Api', '0007_schooldetail_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdetails',
            name='state',
            field=models.CharField(default='On Going', max_length=20),
        ),
    ]
