# Generated by Django 4.1.5 on 2023-06-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12Api', '0008_alter_trainingdetails_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldetail',
            name='grades',
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
